-- USER
DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    ID INT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(32) NOT NULL
  , PASSWORD VARCHAR(32)
  , ANONYMOUS BOOLEAN
  , UNIQUE UQ_USER (NAME)
  , PRIMARY KEY (ID)
);

-- CHATROOM
DROP TABLE IF EXISTS CHATROOM;
CREATE TABLE CHATROOM (
    ID INT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(32) NOT NULL
  , DESCRIPTION VARCHAR(256) NOT NULL
  , PRIMARY KEY (ID)
);

-- MESSAGE
DROP TABLE IF EXISTS MESSAGE;
CREATE TABLE MESSAGE (
    ID INT NOT NULL AUTO_INCREMENT
  , CHATROOM_ID INT NOT NULL
  , USER_ID INT NOT NULL
  , DATE_SENT TIMESTAMP
  , SUBJECT VARCHAR(32)
  , CONTENT VARCHAR(256)
  , PRIMARY KEY (ID)
  , CONSTRAINT FK_MESSAGE_CHATROOM FOREIGN KEY (CHATROOM_ID) REFERENCES CHATROOM (ID)
  , CONSTRAINT FK_MESSAGE_USER FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);
